# Application name
spring.application.name=Ecom-Project

# Database configuration
spring.datasource.driver-class-name=org.postgresql.Driver
# spring.datasource.url=jdbc:postgresql://dpg-d1gbu4mmcj7s73cjg9a0-a:5432/renderdb_vpkv
spring.datasource.url=${DB_URL:jdbc:postgresql://dpg-d1gbu4mmcj7s73cjg9a0-a.oregon-postgres.render.com/renderdb_vpkv}
spring.datasource.username=ecomroot
spring.datasource.password=CD5YRBDBcopMV3dIq8FY9INEnq1VY3ua

#Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Thymeleaf
spring.thymeleaf.enabled=true

# Set max upload file size to 10MB
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# RozarPay Config
# razorpay.api_key=rzp_test_kM7HJJbp7bkdwA
# razorpay.api_secret=kXkcBVwSaTQX7TCmkbB1oxyL

razorpay.api_key=${RAZORPAY_API_KEY:rzp_test_kM7HJJbp7bkdwA}
razorpay.api_secret=${RAZORPAY_API_SECRET:kXkcBVwSaTQX7TCmkbB1oxyL}

app.shipping-fee=0
# Cloudinary configurations
# cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME}
# cloudinary.api_key=${CLOUDINARY_API_KEY}
# cloudinary.api_secret=${CLOUDINARY_API_SECRET}